platform :ios,'7.0'
use_frameworks!

#pre_install do |installer|
 	 # Do something fancy!
# 	$LOCALPATH = "/Users/boo/Documents/fenda_ios/branches/fenda1025/LocalPod"
#end

target 'TestSwiftHBKit' do
 
 pod 'MJRefresh','3.2.0'
 pod 'HBKit',:path=> '../../HBKit.podspec'
# pod 'HBKitRefresh' 
 pod 'HBKitWatchDog',:path=>'../../HBKitWatchDog.podspec'
end
#注释
